### ISSUE TITLE
@oclif/color has been updated to `0.1.0`

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli#85]
This `@oclif/color@0.1.0` release includes the dependency for `chalk` at `^2.4.2`.
Remove our dependency on chalk, `npm pack`, and install from the `.tgz` to test.

related to: https://github.com/adobe/aio-cli/commit/ac756eecd8aca87942b5d0a9ad54fffdd0eb022d

**Comment by shazron** [comment]
Just tried removing this reference from package.json, packing, and installing from the tarball -- doesn't fix it, so somewhere down the line it's still not resolving the dependency properly.

**Comment by DrewML** [comment]
Hey @shazron 👋.

FWIW, when I remove `chalk` from `package.json` on `master` and do `rm -rf node_modules && npm i`, I'm getting `chalk@2.4.2` at the top-level.

There is still `chalk@3.0.0` in the graph, though, because of [`@adobe/aio-cli-plugin-app@1.0.0`](https://github.com/adobe/aio-cli-plugin-app/blob/600b542733d7e12a3c05d712ae79bcd06f54e959/package.json#L13):

```sh
$ npm ls chalk@3.0.0
@adobe/aio-cli@3.0.0 ~/aio-cli
└─┬ @adobe/aio-cli-plugin-app@1.0.0
  ├── chalk@3.0.0 
  └─┬ ora@4.0.3
    └── chalk@3.0.0
```

**Comment by shazron** [comment]
Turns out this is an issue with the `@oclif/plugin-plugins` still, due to a misunderstanding of semver (which tripped me up as well, since I assumed it understood it for `^0.0.0`) 

See my latest comment: https://github.com/oclif/plugin-plugins/issues/86#issuecomment-606356298
